import ArrowUp from './arrow-up.vue'
import ArrowDown from './arrow-down.vue'
import ArrowLeft from './arrow-left.vue'
import ArrowRight from './arrow-right.vue'
import DArrowLeft from './d-arrow-left.vue'
import DArrowRight from './d-arrow-right.vue'
import Clock from './clock.vue'
import Calendar from './calendar.vue'
import TableFilter from './table-filter.vue'
import {
  Back,
  CaretRight,
  CaretTop,
  Check,
  CircleCheck,
  CircleCheckFilled,
  CircleClose,
  CircleCloseFilled,
  Close,
  Delete,
  Document,
  FullScreen,
  Hide,
  InfoFilled,
  Loading,
  Minus,
  More,
  MoreFilled,
  PictureFilled,
  Plus,
  QuestionFilled,
  RefreshLeft,
  RefreshRight,
  ScaleToOriginal,
  Search,
  SortDown,
  SortUp,
  Star,
  StarFilled,
  UserFilled,
  View,
  WarningFilled,
  ZoomIn,
  ZoomOut,
} from '@element-plus/icons-vue'

export {
  Back,
  CaretRight,
  CaretTop,
  Check,
  CircleCheck,
  CircleClose,
  Close,
  Delete,
  Document,
  FullScreen,
  Hide,
  Loading,
  Minus,
  More,
  MoreFilled,
  PictureFilled,
  Plus,
  QuestionFilled,
  RefreshLeft,
  RefreshRight,
  ScaleToOriginal,
  Search,
  Star,
  StarFilled,
  UserFilled,
  View,
  WarningFilled,
  ZoomIn,
  ZoomOut,
  CircleCheckFilled,
  CircleCloseFilled,
  InfoFilled,
  SortDown,
  SortUp,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  DArrowLeft,
  DArrowRight,
  Clock,
  Calendar,
  TableFilter,
}
